[profile.default]
src = "contracts/src"
test = "contracts/test"
script = "contracts/script"
out = "out"
libs = ["lib"]
solc = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = true
fs_permissions = [{ access = "write", path = "./deployments" }]

[rpc_endpoints]
monad_testnet = "https://testnet-rpc.monad.xyz"
monad_mainnet = "https://rpc.monad.xyz"
arc_mainnet = "https://rpc.mainnet.arc.io"
base_sepolia = "https://sepolia.base.org"
arbitrum_sepolia = "https://sepolia-rollup.arbitrum.io/rpc"
ethereum_sepolia = "https://ethereum-sepolia-rpc.publicnode.com"

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
